default_stages:
  - commit

repos:

# these lines taken from https://pre-commit.com/#advanced
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=79]
