on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  test:
    runs-on: ${{  matrix.os  }}
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.9"
          - os: ubuntu-latest
            python: "3.10"
          - os: ubuntu-latest
            python: "3.10"
            pip-flags: "--pre"

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      # Check
      - name: Install requirements
        run: |
          pip3 install -r requirements.txt
      - name: Set up pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ matrix.python }}|${{ hashFiles(format('{0}/.pre-commit-config.yaml', env.PROJECT_ROOT)) }}
      - name: Run pre-commit
        run: |
          pre-commit run --verbose --color=always --show-diff-on-failure --all-files
      
      - name: Test with pytest
        run: |
          python -m pytest

